name: CI/CD

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace with your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install pyYAML
          pip install cython
          pip install -r requirements.txt
          pip cache purge

      - name: Run Flask Application
        run: |
          python app.py &  # Run Flask application in the background
          sleep 5  # Wait for Flask to start (adjust as needed)
          echo "Flask application started"

      - name: GitHub Deployment
        run: |
          mv build/* docs/