name: CI/CD

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace with your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pip setuptools wheel
          pip uninstall -y setuptools
          pip install setuptools
          pip install -r requirements.txt  # Adjust as per your requirements

      - name: Start Flask Application
        run: |
          python app.py &
          mv build docs
          sleep 3  # Allow time for the Flask app to start

      - name: Github Deployment
        run: |
          # Additional deployment steps if any

