name: CI/CD

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace with your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --upgrade pip setuptools wheel
          pip cache purge
          sudo apt-get install python3-dev build-essential


      - name: Start Flask Application
        run: |
          python app.py &
          mv build docs
          sleep 3 

      - name: Github Deployment
        run: |
          # Additional deployment steps if any

